#!/bin/sh
dir=`pwd`
projectName=`basename $dir`
cd ~/work/esp/esp-idf
/bin/sh . ./export.sh
cd $dir

~/work/esp/esp-idf/tools/idf.py build
if [ $? -ne 0 ]
then
    echo "Exit"
    exit 1
fi
echo "Flash app"
openocd -d2 -s ~/.platformio/packages/tool-openocd-esp32/share/openocd/scripts \
-f interface/ftdi/esp32_devkitj_v1.cfg \
-f board/esp-wroom-32.cfg \
-c "program_esp32 build/${projectName}.bin 0x10000 verify" \
-c "reset run; shutdown"
 
