#!/bin/sh
echo "Reset ESP32"
openocd -d2 -s ~/.platformio/packages/tool-openocd-esp32/share/openocd/scripts \
-f interface/ftdi/esp32_devkitj_v1.cfg \
-f board/esp-wroom-32.cfg \
-c "reset run; shutdown"

echo "Start monitor"
idf.py -p /dev/ttyUSB1 monitor


